### ISSUE TITLE
isn't it connecting to same room?

### ISSUE THREAD

**Issue by kashif-raza2019** [joraavanes/chatify#1]

**Comment by kashif-raza2019** [comment]
I have been trying to connect with room having same name (value) but it only shows that room in other rooms menu!

**Comment by kashif-raza2019** [comment]
Well can i join with you for creating it more robust and functional, I have been working for this kind of app too using socket.io

**Comment by joraavanes** [comment]
Hi there

My pleasure to have you on this project.

There might be a problem with the name of the room. I trim and lowerCase and replace spaces with hyphens as the new room gets added (on the backend though).

what names have you used to create a room?

**Comment by joraavanes** [comment]
Although I added a feature to Join component to show the current live rooms to select from them easily. (not pushed to heroku server yet)

**Comment by kashif-raza2019** [comment]
> Hi there
> 
> My pleasure to have you on this project.
> 
> There might be a problem with the name of the room. I trim and lowerCase and replace spaces with hyphens as the new room gets added (on the backend though).
> 
> what names have you used to create a room?

Thanks,
Okay, Well I have named as Room 1 & named as ABC and XYZ

**Comment by kashif-raza2019** [comment]
> Although I added a feature to Join component to show the current live rooms to select from them easily. (not pushed to heroku server yet)

Oh great Well I am searching for people who have been or are already working with socket.io, I have a repo (Empty) as Live-Chat in which i am developing the 1 to many user chat application system in which chats are encrypted (Major Work) with MD5 Hashing, with the functionality to have Video Call 1-1 (For Now and later adding Group Call too!)  If you want to work with me too Feel free to contact. https://github.com/kashif-raza2019/Live-Chat.
Regards,

**Comment by joraavanes** [comment]
That sounds cool. I am looking forward to that... gonna check it out soon.
Thanks for the contact,

**Comment by kashif-raza2019** [comment]
My Pleasure!
